quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Reactive Incident Dispatch API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API reativa para despacho e triagem de incidentes operacionais.
quarkus.smallrye-openapi.info-contact-name=Luis Fabricio
quarkus.smallrye-openapi.info-contact-url=https://www.linkedin.com/in/luisf-fabricio/
quarkus.http.enable-compression=true
